apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: apac-gitops-demo
  owner: apac-gitops-demo
  parentdir: .
  protocol: https
  repo: cp4i-gitops-apps.git
  url: https://github.com/apac-gitops-demo/cp4i-gitops-apps.git
