apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgCMRlI16XZGB11zfhHcaDloIYtHTIyac7ILQWM3KIksO7aW80l8jBlHCXZhYI1ivFmjmugusM/01KQYGWE4mMM+AvZ6IQEp4YyZnUUiQ+jfM8grBDovIP4az2BEi2ZjrDPamniPg6NwmZb9yY4qQhCxKkaQqVEwg9h0vR1lkzo3MI8FlvyBIlrkLp7umgH0BN+rQrQtomQrtEF2r/8AW6JnzeToqQgEgbiTkUXZNpjMo/dV90gcCLEstIuIJppFGsyOIZXtndG+uEc8ksKtz5Y6TH3wYb48nezAKTw8ZUxLHwr93xpXw9FyeEYHb5DF+nyX+9auo6HwkQKLa/Or2rdWeowkNhbb/EnpbkTAxNSQPFZAVgndxCJf0pk32CG5vpKFHWhTdKrSt1zbmPtpoEi4MUdRPmiKILzjdaGaI2qDxXS6lcF2DudBHO5U2/VAy0fHI+YPc3k+u0nTRFT9zAT09//CD3fa0qWi+OXyz/2TTpChjMe0ohtItvAxnkze+E+UFnBjiVq+GVo8C2jItpW7sh90w7XWHXsHL7B3/0pJpMWgimVdOLBTpKuhi3ocOxOW6wJN4enX2PHOEipTx0QqUns9MwmzWdWc3+DwDNeEucPOw7rRik/FFXwIovr9VO+MMWJVVBuIWJXc0lvd/8SE44Ct28Cf5i169Hm2TResdeLxuCjJyE7gv//dYYdAo4TXtv1+5fXU7dxyzmHy3aTC2wnc+eYix9CjWVTuA/K4V3eYose/BA==
    ARTIFACTORY_PASSWORD: AgDIlm4LpfIa0ZTKOeN9J+1Jemtg07k5/69VXjxu2ZZ1oxm7j1BDZKXeiq/DUvz3U81yIhBgYLOwsrgl6zCEIwKdkANFaAts3B1q8KD4RuT/wch8fhuSnmavkKw3FsjWonaTdYuDA3QaclRwWyi8NVxqfrBAu/e5CUeU6uMLH6pP9mW2s6vQQeh8PKZZx1KvWtulIK8Zk1pIUyY2g75qihhQizln9VU2WqmZabyX1xGIsS8jVDSFSyXjFP2iM9NcHC1WyJt3MMueGzdyG/boQbR2ctMjI/lvinkGIY3o5CrT/3EC3N/ZTaG8aaTidqCEk6HSy2KmPE26/jQF437+Eq8iHrGK5+7HPuRBl/4h2bnQSwKdT+0P90s6myNK9wZ9N3rQ99Ae4cS4x/qsyKCT/RUrMFVmz395ollh1Aa70CEggr6J9afWX8VyhTV7ImbGpuIOZlAmikdXfcxPvsY2RjixbLQv/I3xFLFvUSfvaFmW7QHK/A8YMC6yFlpz5K5cyyqptp9JxpVOEyH1I6NG1vN0ut8OongEtGqx2SUfkwt29FHF5BuSv4L/4e9JaPTqqr/+qWSQ0TuL0BxRedAPby+dzVqmFSBjo5RwOluQUr6Att5l9jVgHvKWvOv7FUqOHx2ocpfCpbf2URk66bFSDdnNOQGG3lwPWYUBBetlfdaqj576hf4XfEmbGmGvoLwykzHOn5ljh/xmMyrc5h1zFLiluCYGrQ==
    ARTIFACTORY_URL: AgAtZuOBnc+7hs2WewNBEZTdoTjdpOH2T1rlKdhgWwQmaW6ZiWCZtTQwwjDFEw4bH9WEjD0NIkuO6HGAmgi6hHe5XjAVFu1Ig1K0QdsmcofrYerMlGAFd9WiNQ03leCooEyHnOzW+SpXyVeWxDpl1qcUdc5NqDiJ8N9XCeUfOObbKi7bhIeWQUEmhtSAgO1XHr4Ufx5+8SKSBYD6fGQnE15LyBkaQ0HceFdAX1lhIAc3OHxBzEXbWJnhibYVZBnnSGcY0c5wDBuxl6sP0IgYdekmcVV9Db/QTnrX0IMm9zylBeICQRWHb65j85tZQ/IYSmwcYJqXG8mS1X2nKAtKQhYdSWMJhIl0Y8kGKaLzWr2Wa3OsGaXHjUmAcwJm90KfQ0UzWVvhZEJuToN5D3nNl6h+pmZNFEAlVaSQubmJFruTvGg17Fx1CSjhCJfs1PsfxKW+xAL/xZG0hhZd31JceDIVPjBnl4bfllSndrz8hkQRHpJaiG0J9Sj1QsN/y4Ojz/pGPRBz7hWu/s/Q0zWd4KYSP1Gqu2h+d0ngcxh9ei5Ct7mFzuf9KCPwa1fkSsaouUDjy7AmLAtjW9Udy9z7Nzm9QmE7pNzhLjI5EM8eWWzKaKmWdGdxkeIVtv6iVP6mssvxcrB+Y5Oh2Sx8DAPcOjaf3QMAkvjRrhRTGtvDrx8gFp9XT3BErbwwB80zXIkG4nyAe+14u4EmWCqUwnkP99wllEVsYgTx4o/rM9icr23j+BbPM6fu123phg==
    ARTIFACTORY_USER: AgBjUg5IrPF4yT9Ir9Iqg/auWuefTQDVqU9UAZsGIYeMsHpGDX3AJlFBbIGSKLtVhdLriZu2x+iIK+xzpm2W9kIQwdeIKOv0E03V+vCKDxWKfUw3srIno+rfOLwUW1EXJOtyAuhOT8Yeo9uE/lIAI3dJrFRjV7cTNaCcPygG/ztqefmmSmDFQxjZKZh0glu5sS9WXxpptgUWoddwXuPbwysHtJPsrso938SU+RlgTTtqwI4BvZjeXvqHoWTnT5FDlc5XIiMrWhTxm3+qxy+rkB7oRryfmAVxyvSlXmJHJpHea3fH3JsHmv1bvJTtPe7c26zkh6xIhpEpLUlm7IYoy6W4xC6yispD8rFnsUkCE6o+184ZJu+cX1dxpTX2UgUU/nC/fDs2Ms0gUU4XVZTZVe/ryuG2XCaBfio10VezxaO/yr/CVut7EATtUTpuAys1O3kLcokL1E9S+R0x7HvtEAW17yhnG5IqC81v4XRAM0ufPO10sPoBPDP7XX+V8xr9N6IDRqHHsVEtZVndQsU7DtW/W98yBfMFxW1uwy77AS9U2Ri6IeG2x+52WM4bkiGbGjR9dNazYPtA0sQdIEdWYt03PG6YbNVtzMeADMtqRc79w/CD30EJQmLcmmLFec6JrM62VNYAlHGBS8haF+90b+pfKAwWm4b9p2lgQ28bl45XnqTS1MzDXrFJJHaljittLutJ79Tr3g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-10-29T00:46:03Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-10-29T00:48:11Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

